### ISSUE TITLE
(URGENT) Build broken on macOS

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/homebrew-metanorma#82]
@CAMOBAP can you please help fix this? Thanks.

**Comment by CAMOBAP** [comment]
macOS build is working, also I have reported/created some PR/issues
 - https://github.com/metanorma/packed-mn/issues/194
 - https://github.com/metanorma/metanorma-cli/pull/296

There is still not clear why `brew test` fails with Jing issue because this issue is resolved in jing already https://github.com/sshaw/ruby-jing/pull/5
But I think we will change the testing approach after https://github.com/metanorma/metanorma-cli/pull/295 merge and use test matrix
